No errors showing. Using Configurable trait now.
webbuilders-group/silverstripe-packagistshortcode pull request #6
Opened 2019-05-21 14:57 UTC by w0299208

2019-05-21 15:06 UTC, UndefinedOffset requested changes
It looks like a number of files came from the webbuilders-group/silverstripe-githubshortcode module, why did these get added? There should be equivalents of these files in the module.

2019-05-21 15:06 UTC, UndefinedOffset commented on _config/config.yml
> +WebbuildersGroup\PackagistShortCode:
This is incorrect it should be `WebbuildersGroup\PackagistShortCode\PackagistShortCode`

2019-05-21 16:22 UTC, UndefinedOffset requested changes
Can you also update the README.md in the root (the configuration options section to be specific) just needs the namespace added.

2019-05-21 16:22 UTC, UndefinedOffset commented on src/PackagistShortCode.php
> +        Requirements::css('webbuilders-group/silverstripe-githubshortcode:css/GitHubButtons.css');
This should be `webbuilders-group/silverstripe-packagistshortcode:css/PackagistButton.css`

2019-05-21 16:22 UTC, UndefinedOffset commented on src/PackagistShortCode.php
> +        // return $ssViewer->process($obj);
Something tells me with this removed this does not render at all

2019-05-21 16:41 UTC, w0299208 commented on src/PackagistShortCode.php
> +        // return $ssViewer->process($obj);
Indeed! I thought these lines were doing something else. Fixed in the next commit.

2019-05-23 16:35 UTC, UndefinedOffset requested changes

2019-05-23 16:35 UTC, UndefinedOffset commented on README.md
> +WebBuildersGroup\PackagistShortCode\PackagistShortCode:
So minor... but it will cause issues `WebBuildersGroup` must match the case defined as the namespace `WebbuildersGroup`

2019-05-23 16:41 UTC, UndefinedOffset approved these changes

2019-05-23 16:42 UTC, merged